### ISSUE TITLE
Documenting the switch from bootstrap to boot

### ISSUE THREAD

**Issue by iagomosqueira** [ices-tools-prod/TAF#13]
Like in <https://github.com/ices-tools-prod/TAF/blob/main/R/taf.boot.R#L57>

is this still the case?

**Comment by arni-magnusson** [comment]
The slightly confusing/misleading name 'bootstrap' has been mildly criticized over the years, but the development team couldn't think of a better name for a while. When it was discussed by WGTAFGOV some years ago, Jose De Oliveira finally identified a solution: to rename it to 'boot'. The conclusion at WGTAFGOV was that this would indeed be an improvement, but a low priority one, which should only be introduced if it could be implemented with minimal inconvenience for users.

The development team agreed with that conclusion. It's a nuisance to have to explain at every TAF workshop that taf.bootstrap() and the bootstrap folder are not related to statistical bootstrap, which is how fisheries scientists interpret the term. Instead, it's related to booting a computer, which is why the function name taf.boot() and a boot folder would make more sense. Last month at a conference, I was looking for some simple tasks that I could work on while listening to presentations and engaging in discussions. The bootstrap->boot conversion was perfect for that, so after a review with the TAF development team, it's now finally done in version 4.2.

We hope that this change does not cause significant inconvenience or confusion for users, so I'm eager to clarify or improve anything related to your question. We were happy to find a simple and reliable implementation, based on a utility function boot.dir() to help TAF find the boot directory. The boot.dir() function, effectively a one-liner, is used by other TAF functions but the general user won't need to use it.

The idea is that the user can work exactly as before and may not even notice the change. All previous analyses run as before, so we have full backward compatibility. The analysis can have a bootstrap folder or a boot folder, and the user can run taf.bootstrap() or taf.boot(). The only function that indicates a preference is taf.skeleton() that produces a boot folder. TAF and icesTAF 4.2 pass a suite of tests https://github.com/ices-taf-dev/boot-tests that confirm backward compatibility. In summary, although the documentation mentions that the term ['boot' is now preferred](https://github.com/ices-tools-prod/TAF/blob/7c01551/R/taf.boot.R#L57-L62), we expect this to be a gradual transition, with no extra work required from the general user.

Now, on the other hand, you are not a 'general user' by any means - and for that I'm grateful :) You've been using TAF for a variety of innovative analyses, testing the fullest extent of technical capabilities, contributing to the package, and teaching people how to use it. This is why I want to provide the above clarifications regarding the bootstrap->boot transition, more detailed than the 4.2 news entry. Let us know if there's anything that is unclear or could be improved.

**Comment by iagomosqueira** [comment]
Thanks for very long explanation. I was one in favor of the change, and in fact had started using the new convention already.

Happy to be considered an 'awkward' user of TAF :-)

I just thought the agreement at WGTAFGOV was to keep the current convention, and so was surprised to see the new one as 'recommended'. This lead me to think whether the separation between the `TAF` and `icesTAF` packages could be useful here. In ICES decides to stick to 'bootstrap' as first option, it can do so by having it as default in `icesTAF` functions, while `TAF`, as the more general engine could provide multiple options and even have a different one as default.

**Comment by iagomosqueira** [comment]
And next time I will make the question more clear and specific, although maybe not if that means not getting the full long explanation. Many thanks for that, honestly.
